docs: add guide documentation
janhq/jan pull request #1184
Opened 2023-12-24 18:39 UTC by hieu-jan

2023-12-26 00:24 UTC, 0xSage commented on docs/docs/guides/03-chatting/02-upload-docs.md
>  ---
Insert a `info` section: similiar to: https://jan.ai/developer/build-assistant/your-first-assistant/

2023-12-26 00:39 UTC, 0xSage requested changes
A few nits. Can we try to get this PR in asap.

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/03-upload-images.md
> +  ]
Insert info section, similar to https://jan.ai/developer/build-assistant/your-first-assistant/

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/01-start-thread.md
> +A thread title acts as a name for your thread. It appears on the left side of the chat window, helping you easily navigate through your interactions. If you do not set a thread title, Jan will set it
Missing screenshot

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/01-start-thread.md
> +On Jan, you can set assistant instructions that guide the responses of your assistant. These instructions are set at the conversation level. Globally, as default, assistant instructions will apply to
This is confusing. 

Break into two secitons please: 

1. Setting Assistant Instructions (at the thread level)
2. 1. Setting Default Assistant Instructions (at the global level)

Then include screenshots.

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/01-start-thread.md
> +Jan offers a variety of models to suit your conversational needs. Each model has its unique characteristics and capabilities. You can choose a model that best fits your needs via the hub and download
Missing the following info: 

1. Currently, you can only change models in a new thread. After a thread is initiated, you can't change models.

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/01-start-thread.md
> +You can customize the model params for your thread e.g. setting a customized value of max_tokens value for your thread, etc.
Missing: 

1. Changing model configs at the thread level
2. Changing model configs at the assistant level
3. Changing model configs at the global/default level

Include screenshots for users - this feature has been a source of great confusion (our fault)

<img width="779" alt="image" src="https://github.com/janhq/jan/assets/69952136/e9d334ab-e5bf-4279-bfcc-27f3aea5350d">

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/04-manage-history.md
> +## Delete Thread
Missing section: 

## Managing Threads via Folders
1. Indicate to users they can directly access both thread history and thread configs via their folders. 
2. Show them how to `reveal in finder` `view as json`
3. etc.

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/README.md
> +This guide is designed to help you maximize your experience with Jan, covering everything from starting engaging threads to managing your chat history effectively.
Thanks for this. Very helpful to have this.

2023-12-26 00:39 UTC, 0xSage commented on docs/docs/guides/03-chatting/README.md
> +- [Manage chat history](manage-chat-history)
I can't leave a comment directly in the gifs, but I think it's more helpful to record gifs in lightmode. Our darkmode is kinda hard to read at the moment.

2023-12-26 02:23 UTC, 0xSage commented on docs/docs/guides/03-chatting/README.md
> +- [Manage chat history](manage-chat-history)
Non blocking for this PR. Just pls note for future.

2023-12-29 04:58 UTC, 0xSage requested changes

2023-12-29 04:58 UTC, 0xSage commented on docs/docs/guides/03-chatting/01-start-thread.md
> +A thread title acts as a name for your thread. It appears on the left side of the chat window, helping you easily navigate through your interactions. If you do not set a thread title, Jan will set it
Hey, let's treat our users with respect. 

Assume that users (like us) are lazy but smart. 

Meaning, we don't need to explain simple things like "A thread title is a title of a thread."

I'd like this entire PR to be 50% more concise. 

Please pass your copy through Jan assistant iwth the instructions "Help me rephrase these user guides to be more concise and helpful."

2023-12-29 04:58 UTC, 0xSage commented on docs/docs/guides/03-chatting/01-start-thread.md
> +Jan offers a variety of models to suit your conversational needs. Each model has its unique characteristics and capabilities. You can choose a model that best fits your needs via the hub and download
Again, please split into 2 sections, with a screen recording for both

2023-12-29 04:58 UTC, 0xSage commented on docs/docs/guides/03-chatting/04-manage-history.md
> +Jan offers a convenient and private way to interact with a conversational AI locally on your computer. This guide will walk you through how to manage your chat history with Jan, ensuring your interac
First sentence is not related to this page. 

Isn't the main message more of: Jan persists your app usage locally on your filesystem, so your data never leaves your computer. This guide will walk you through how to direct manage your application files...

2024-01-02 16:19 UTC, 0xSage commented
1. I think the chatting section is missing a major user guide teaching users that **they need to download a model from the Hub first**. The ordering of these pages need to be improved. 

2. Also, a lot of the screenshots in the /chatting pages say "You don't have a local model yet".

2024-01-05 00:53 UTC, hieu-jan commented
Note: Temporary hide starting thread and taking all current issues in the other PR. There are some changes in current UI of starting thread. Will need to re-documentation this part and record based on new UI.

2024-01-05 02:35 UTC, hieu-jan commented
Note: Temporary hide starting thread, not ready docs for models and taking all current issues into consideration in the other PR. There are some changes in current UI of starting thread. Will need to re-documentation this part and record based on new UI.

2024-01-05 05:45 UTC, 0xSage approved these changes

2024-01-05 05:46 UTC, merged