docs: add pointing client remote server
janhq/jan pull request #1288
Opened 2024-01-02 09:03 UTC by hieu-jan

2024-01-02 15:33 UTC, hiro-v commented
This particular PR does not show the user the way to use existing OpenAI API. It only show how to add `OpenAI compatible API endpoint`. I think it should be improved

2024-01-03 05:07 UTC, 0xSage requested changes

2024-01-03 05:07 UTC, 0xSage commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +## Configuring Client Connection to Remote/Local Server
Shouldn't this be a new page in docs?

2024-01-03 05:07 UTC, 0xSage commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +## Configuring Client Connection to Remote/Local Server
Move it under a new section

**Integrations**
- Integrating with a Remote API (OpenAI integration tutorial goes here)
- Integrating with a Local Server (LMstudio integration tutorial goes here)

2024-01-03 05:07 UTC, 0xSage commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +In this guide, we will show you how to configure a client connection to a remote/local server, using LM Studio as an example.
In this guide, we will show you how to configure Jan as a client and point it to a remote server. 

We'll use OpenAI API as an example, although this would work with any remote & local (self-hosted) API server endpoint (link to Integrating with a Local Server).

2024-01-03 05:07 UTC, 0xSage commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +At the moment, you can only connect to one compatible server at a time (e.g OpenAI Platform, Azure OpenAI, LM Studio, etc).
Let's use OpenAI api as an example. It is more common.

2024-01-03 05:07 UTC, 0xSage commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +Navigate to the `~/jan/engines` folder and modify the `openai.json` file. Please note that at the moment the code supports any openai compatible endpoint only read `engine/openai.json` file, thus, it
Again, use openai as an example, otherwise its super confusing. Why am I using openai.json to integrate with another local server not from openai?

2024-01-03 05:07 UTC, 0xSage commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +### 2. Create a Model JSON
I think we should use Ollama as an example instead of LMStudio - it has more developer adoption and is really easy to run as a local server.

2024-01-04 03:15 UTC, hiro-v approved these changes

2024-01-04 03:19 UTC, hieu-jan commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +  "full_url": "http://<REMOTE_LMSTUDIO_IP>:<REMOTE_LMSTUDIO_PORT>/v1/chat/completions",
Thanks for your feedback. I made a change of full_url on new version!

2024-01-04 03:38 UTC, 0xSage approved these changes

2024-01-04 03:39 UTC, merged