Feat: Add good small models as a starter for low resource machines
janhq/jan pull request #1543
Opened 2024-01-12 03:53 UTC by hahuyhoang411

## Describe Your Changes

Add 1-3B models with good coherent.

## Self Checklist

- [ ] Stable Zephyr 3B
- [ ]

2024-01-15 17:00 UTC, hahuyhoang411 commented on models/stable-zephyr-3b/model.json
> +      "prompt_template": "<|user|>{prompt}<|endoftext|><|assistant|>"
ah yes, it was my mistake. Thank you for pointing out

2024-01-16 11:20 UTC, tomasmcm commented
Not many people have 30GB of RAM available to run the Mixtral models 🙈 Can we merge this without that? Having stable-zephyr and dolphin-phi would already be a great improvement.

2024-01-17 06:16 UTC, louis-jan requested changes
Just a reminder, let's update model-extension's version

2024-01-24 09:17 UTC, hahuyhoang411 commented
Prepare to merge with https://github.com/janhq/jan/pull/1659

2024-01-24 09:20 UTC, closed without merging