feat: HTTP proxy support
janhq/jan pull request #1562
Opened 2024-01-13 00:11 UTC by markmehere

## Describe Your Changes

This adds requested proxy support although not SOCKS nor PAC support.

If you can decipher those acronyms you may know more about proxies than me.

It includes all changes from #1558 and the two work well in combination as many proxies invalidate end-to-end security.

Self-signed/unverified certificate support is understandably disabled by default - although on a certificate error the user will be notified of the setting.

Proxies must begin with `http` at all-levels to work or be saved to preferences.

To test proxy support:

```sh
brew install mitmproxy
mitmproxy -p 9028 --set stream_large_bodies=1m    # stream_large_bodies very important
make dev
# set HTTPS proxy to http://127.0.0.1:9028
# enable Ignore SSL certificates
# download a model and observe
```

Feel free to merge and edit - as it's your project! 🙂

## Screenshot

![proxy-working](https://github.com/janhq/jan/assets/52765023/e48cc442-8dbf-498b-8f9d-9256bd119967)

## Fixes Issues

- #1512 
- #1074 
- #1040 
- #1558 

## Self Checklist

- [x] Added relevant comments, esp in complex areas
- [x] Updated docs (for bug fixes / features)
- ~Created issues for follow-up changes or refactoring needed~

2024-01-13 02:52 UTC, 0xSage commented
Wow thank you so much for this PR! We'll take a look latest Monday. 🙏 ❤️

2024-01-17 03:03 UTC, namchuai commented
Overally looks good to me. Please put your comment @louis-jan

2024-01-17 04:50 UTC, louis-jan commented on web/context/FeatureToggle.tsx
> +      localStorage.getItem(HTTPS_PROXY_FEATURE)
Proxy prefers not to be null; localStorage.getItem(HTTPS_PROXY_FEATURE) might return null

2024-01-17 04:52 UTC, louis-jan requested changes
That's an awesome PR.

Please help resolve the error and rebase dev again.

Thanks

2024-01-18 05:56 UTC, louis-jan commented on web/context/FeatureToggle.tsx
> +      localStorage.getItem(HTTPS_PROXY_FEATURE)
@markmehere, that's a really great PR. I'd like to apply this change to fix the compilation error, and then we'll be good to go.
```suggestion
      localStorage.getItem(HTTPS_PROXY_FEATURE) ?? ""
```

2024-01-19 02:39 UTC, hiento09 approved these changes
LGTM, thank you so much, @markmehere, for dedicating your time to contributing to our repo.

2024-01-19 03:10 UTC, louis-jan approved these changes

2024-01-19 03:25 UTC, merged

2024-01-19 11:12 UTC, markmehere commented
Cheers guys. Looks good. I had some build troubles - still trying to figure out why builds work on one machine and not the other. 😁

2024-01-22 06:54 UTC, Van-QA commented
tested and looking good via the testing on Jan v0.4.4-160
<img width="1891" alt="image" src="https://github.com/janhq/jan/assets/64197333/4fd059a4-cae8-4b65-9453-fe33bfd57caf">