Simplify sidebar, header, responsive UI
janhq/jan pull request #163
Opened 2023-09-12 07:15 UTC by drakehere

- The left sidebar layout has been updated with a new layout
- Header is removed for desktop size
- Hover state added

2023-09-12 09:41 UTC, 0xSage commented on docs/package.json
> +    "yarn": "^1.22.19"
I dont think this is a part of the PR? can you remove the changes in /dcos

2023-09-12 09:59 UTC, louis-jan commented on docs/package.json
> +    "yarn": "^1.22.19"
`yarn` should be a global dependency, should not be in `package.json` cc @namchuai

2023-09-12 09:59 UTC, louis-jan commented on docs/package.json
> +    "yarn": "^1.22.19"
also discard package-lock changes

2023-09-12 10:01 UTC, louis-jan commented on web-client/app/_components/ConversationalList/index.tsx
> +      <p className="text-xl dark:text-white dark:text-white">
duplicated `dark:text-white`

2023-09-12 10:01 UTC, 0xSage requested changes

2023-09-12 10:02 UTC, louis-jan commented on web-client/app/_components/Header/index.tsx
> +{/*         <div className="hidden items-center gap-2">
Don't be hesitate to remove (rather than just comment out) (y)

2023-09-12 10:10 UTC, dan-jan commented
@louis-jan @namchuai I experienced a non-fatal Frontend crash due to an expired Keycloak token. Do we need any special handling code for this? (e.g. recover gently on frontend, log user out on FE etc?)

![image](https://github.com/janhq/jan/assets/101145494/ee7665f1-87e4-4feb-97f6-d459830a2993)

2023-09-19 03:52 UTC, 0xSage commented
closing as our UI is changing and stacck has changed

2023-09-19 03:52 UTC, closed without merging