draft: added changelog and posthog
janhq/jan pull request #193
Opened 2023-09-21 15:10 UTC by Its-Alamin-H

2023-09-27 14:18 UTC, 0xSage commented
Is this ready to be reviewed? IF so, pls resolve conflicts, undraft the PR,  and tag a reviewer

2023-10-01 16:12 UTC, Its-Alamin-H commented
> Is this ready to be reviewed? IF so, pls resolve conflicts, undraft the PR, and tag a reviewer

conflicts resolved

2023-10-02 04:29 UTC, 0xSage requested changes

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +  onBrokenLinks: "ignore",
No, we shouldn't leave in broken links

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +  url: "https://docs.jan.ai",
This is no longer the correct link. It's just jan.ai

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +  tagline: "Self-hosted AI inference platform",
Run your own AI

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/authors.yml
> +Daniel:
No, take out this entire page. I don't want hardcoded contributor content when Github already shows who the contributors are

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/Jan v10.md
> +---
rename folder from "blog" to "changelog" please

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/Jan v10.md
> +title: JanAI v1.0
This is wrong. 
1. We're "Jan" not "JanAI"
2. The version is incorrect. Are you tracking the releases here: https://github.com/janhq/jan/releases

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/Jan v10.md
> +authors: [hiento09, Louis, Daniel, automaticcat, namvuong, Nicole]
skip this field

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/Jan v10.md
> +Stay Updated with JanAI: Explore Our Latest Changelog.
"Jan"

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/Jan v10.md
> +### 🎉 We're thrilled to introduce the first version of Jan Web!
Is this content just a placeholder? We're not doing Jan Web. 

Let's structure changelog content like this: https://docs.docker.com/desktop/release-notes/

2023-10-02 04:29 UTC, 0xSage commented on docs/blog/Jan v10.md
> +What is Jan Web, you ask? It’s pretty much a web version of our Jan Mobile, that lets you generate amazing art via Open Source AI Models as well as engaging with the most popular AI Chatbots in the m
Sounds overly promotional. Changelogs should be factual

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +                label: "Developer",
where does this go? out of date?

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +                label: "Getting Started",
where does this go? out of date?

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +      apiKey: process.env.POSTHOG_API_KEY || "DEV",
Are you coordinating with @hiento09 on what the API key is/where we're storing it?

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +
this is out of date

2023-10-02 04:29 UTC, 0xSage commented on docs/docusaurus.config.js
> +            position: "left",
this is out of date

2023-10-10 04:12 UTC, closed without merging