Docs
janhq/jan pull request #2008
Opened 2024-02-13 07:19 UTC by cahyosubroto

## Describe Your Changes

In this pull request, I focused on enhancing the overall user experience and accessibility of the documentation website. Here are the key changes:

1. **Added Quickstart Documentation:**
   - Included detailed Quickstart documentation to help users get started quickly.
   - Modified the configuration file to ensure the Quickstart menu appears in the Navbar, improving navigation.

2. **Revamped Homepage Design:**
   - Introduced a new design for the homepage to enhance visual appeal and user engagement.

## Fixes Issues

- None

## Self Checklist

- [] Added relevant comments, especially in complex areas.
- [x] Updated documentation to reflect the changes made.
- [ ] Created issues for follow-up changes or refactoring needed.

*Additional Notes:*
Include any additional information that might be helpful for reviewers, such as specific challenges faced, notable decisions made, or any dependencies introduced.

cc: @aindrajaya

2024-02-13 08:30 UTC, 0xSage commented
@hiento09 for when you're back. Is there a way to enable autodeploy to github pages, with our ci, so we can preview the docs contributions?

2024-02-14 07:41 UTC, 0xSage requested changes
Thank you - left a few change requests

Suggestion: it's probably easier to work on smaller PRs, in order to get unblocked and generally move faster

2024-02-14 07:41 UTC, 0xSage commented on docs/docs/quickstart/changelog/0.2.0.mdx
> + - feat: Add Jan Hacker House event page to Docs
I like including the changlog in our docs - it highlights how fast our codebase moves. 

However, manually copying this info is redundant, since we can just point users to the github release pages.

Is there a way to automate this, or just do a simple link-out.

2024-02-14 07:41 UTC, 0xSage commented on docs/docs/quickstart/install.mdx
> +        ### Stable Releases
formatting, indentation seems off?

2024-02-14 07:41 UTC, 0xSage commented on docs/docs/quickstart/models-list.mdx
> +# Supported Models
We support all GGUF models and more. I like that this page helps with SEO, by including a lot of model names, but I don't want users to get the wrong idea that these are the only models we support. Is there a way to convey both

2024-02-14 07:41 UTC, 0xSage commented on docs/docs/quickstart/quickstart.mdx
> +2. After you run Jan, the program will take you to the Chatting window, with list of threads and each thread is a chatting box between you and the AI model.
Threads, not "chatting"

2024-02-14 07:41 UTC, 0xSage commented on docs/docs/quickstart/quickstart.mdx
> +### Step 2: Select AI Model
This page is helpful. Thanks for including it.

2024-02-14 07:41 UTC, 0xSage commented on docs/src/components/HomepagePrimaryFeatures/index.js
> +                            <p>Lorem ipsum dolor</p>
placeholder text intentional?

2024-02-14 07:41 UTC, 0xSage commented on docs/src/components/HomepageSecondaryFeatures/index.js
> +                                <h3>Praesent vel Felis Vehicula</h3>
placeholder text intentional?

2024-02-14 07:41 UTC, 0xSage commented on docs/static/img/homepage-new/docusaurus-social-card.jpg
why do we need this?

2024-02-14 07:41 UTC, 0xSage commented on docs/static/img/homepage-new/undraw_docusaurus_mountain.svg
seems like we're reincluding a lot of docusaurus default assets with this PR. why do we need these again?

2024-02-15 12:10 UTC, aindrajaya commented on docs/docs/quickstart/changelog/0.2.0.mdx
> + - feat: Add Jan Hacker House event page to Docs
I think we could implement GitHub API to fetch the data from the GitHub Releases page and programmatically input it into Jan AI docs.

2024-02-15 12:10 UTC, aindrajaya commented on docs/docs/quickstart/install.mdx
> +        ### Stable Releases
Will double check it.

2024-02-15 15:14 UTC, 0xSage requested changes
Hey guys, not sure why I was re-requested to review this as there are unresolved comments.

Let's split this PR into smaller ones? Thank you!

2024-02-19 00:30 UTC, cahyosubroto commented on docs/src/components/HomepagePrimaryFeatures/index.js
> +                            <p>Lorem ipsum dolor</p>
Yes it is intentional. Will update it once we have the full doc complete

2024-02-19 00:30 UTC, cahyosubroto commented on docs/src/components/HomepageSecondaryFeatures/index.js
> +                                <h3>Praesent vel Felis Vehicula</h3>
Yes it is intentional. Will update it once we have the full doc complete

2024-02-19 00:31 UTC, cahyosubroto commented on docs/static/img/homepage-new/docusaurus-social-card.jpg
Sorry, will remove.

2024-02-19 00:31 UTC, cahyosubroto commented on docs/static/img/homepage-new/undraw_docusaurus_mountain.svg
Sorry, we forgot to remove them. Will remove it

2024-02-22 07:08 UTC, hieu-jan commented
Hi @cahyosubroto @aindrajaya, as a new update, we recently merge the new structure of main page to dev branch. #1941  with preview available at https://dev.jan.ai/. Thus, some of content in this PR is currently outdated when you open PR from your folk branch to `docs` branch. (`docs` branch is branch of main website jan.ai is only syncing with `dev` after release or urgent content update). Could you point this branch to `dev` branch after re-update the outdated content with new structure?

Because this PR is created from the folk repo (not have an access to Cloudflare API key deployment), when you open the PR, it won't create the preview demo. There are 2 solutions. 
- If you are already add to the repo, please create a new branch from current `dev` branch, then open the pull request. As team, it will auto generate preview demo with Cloudflare api key 
- Otherwise, I just created `docs-pena-team` may be create a pull request from your folk to `docs-pena-team` with update version of outdated content. Then, I can merge to `docs-pena-team` and create PR from `docs-pena-team` to `dev` for generate preview for easily reviewing. 

cc: @0xSage @dan-jan

2024-02-22 12:32 UTC, aindrajaya commented
Thanks, @hieu-jan, for the prompt update and for notifying us about the recent merge of the new main page structure into the dev branch. I will thoroughly review the PR and make the necessary adjustments to ensure that the content aligns seamlessly with the new structure from the dev branch.
The second option is great; I will create a pull request from my fork to "docs-pena-team" with the updated version of the outdated content. Once you've reviewed and merged it into "docs-pena-team," you can create the PR from "docs-pena-team" to "dev" to generate the preview for further reviewing.

cc: @cahyosubroto

2024-02-23 09:55 UTC, closed without merging