docs: add LM studio integration
janhq/jan pull request #2076
Opened 2024-02-18 14:36 UTC by hieu-jan

## Describe Your Changes

- Finalize the docs for Integrating LM Studio with Jan

## Fixes Issues

- Closes #1863 
- Closes #

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

2024-02-18 15:02 UTC, 0xSage commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +With [LM Studio](https://lmstudio.ai/), you can discover, download, and run local Large Language Models (LLMs). In this guide, we will show you how to integrate and use your current models on LM Stud
I think we should give 3 options: 

- use lmstudio as a backend x jan as fe
- jan as be x lmstudio as fe (? is this possible)
- use jan as fe and be and point to models in the lmstudio app folder

2024-02-18 15:02 UTC, 0xSage submitted a review, later dismissed
see comment. then we can lgtm

2024-02-19 00:40 UTC, hieu-jan commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +With [LM Studio](https://lmstudio.ai/), you can discover, download, and run local Large Language Models (LLMs). In this guide, we will show you how to integrate and use your current models on LM Stud
Got it! Let's me test all available options.

2024-02-19 02:20 UTC, hieu-jan commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +With [LM Studio](https://lmstudio.ai/), you can discover, download, and run local Large Language Models (LLMs). In this guide, we will show you how to integrate and use your current models on LM Stud
I added more section that cover section 1 and section 3. Section 2 seems impossible.

2024-02-19 02:46 UTC, hieu-jan commented
For the migrating model from LM Studio, this migrating method is currently compatible with version 0.4.6 (Copying the .gguf model to jan folder and Jan automatically generate model.json).

I will add one more method of guide user create model.json point directly to model path of .gguf downloaded model of LM Studio together when writing docs for issue #2021

2024-02-19 04:56 UTC, hieu-jan commented
[WIP] I will add the docs for entire Ollama, LM Studio with absolute path, and import the model using absolute path all in this PR.

2024-02-20 02:16 UTC, louis-jan commented on docs/docs/guides/04-using-models/03-import-models-using-absolute-filepath.mdx
> +      "url": "<absolute-filepath-of-the-model-file>"
Please note for Windows users: you may encounter issues if using the Copy Path option and pasting it here. The correct URL format should be: C:\\Users\\Name\\jan (with double backslashes) instead of C:\Users\

2024-02-21 02:56 UTC, cahyosubroto requested changes
Thanks for the great work! Please kindly check my suggested changes and comments. Thanks!

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +- Ensure the filename must be `model.json`.
Since we already created ask users to create a `model.json`, I think this is redundant and can be removed.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +- Ensure the `state` property is set to `ready`.
We can be more decisive and use the word set instead of ensure so I suggest to update these to be 

1. Set the `format` property to `api`
2. Set the `engine` property to `openai`
3. Set the `state` property to `ready`

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +- Ensure the `engine` property is set to `nitro`.
Please check the similar comment above. Thank you

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Restart Jan and navigate to the Hub. Locate your model and click the Use button.
1. Restart Jan and navigate to the **Hub**. 
2. Locate your model and click the **Use** button.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Restart Jan and navigate to the Hub. Jan will automatically detect the model and display it in the Hub. Locate your model and click the Use button for trying out the migrating model.
1. Restart Jan and navigate to the **Hub**. Jan will automatically detect the model and display it in the **Hub**. 
2. Locate your model and click the **Use** button to try the migrating model.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Navigate to `My Models` in the LM Studio application and reveal the model folder.
1. Navigate to `My Models` in the LM Studio application and reveal the model folder.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Copy the model folder that you want to migrate to `~/jan/models` folder.
2. Copy the model folder that you want to migrate to `~/jan/models` folder.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Ensure the folder name property is the same as the model name of `.gguf` filename by changing the folder name if necessary. For example, in this case, we changed foldername from `TheBloke` to `phi-2.
3. Ensure the folder name property is the same as the model name of `.gguf` filename by changing the folder name if necessary. For example, in this case, we changed the folder name from `TheBloke` to `phi-2.Q4_K_S`.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Restart Jan and navigate to the Hub. Jan will automatically detect the model and display it in the Hub. Locate your model and click the Use button for trying out the migrating model.
```suggestion
1. Restart Jan and navigate to the **Hub**. 
2. Jan will automatically detect the model and display it in the **Hub**. 
3. Locate your model and click the **Use** button to try the migrating model.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/04-using-models/02-import-manually.mdx
> +Starting from version 0.4.7, Jan supports importing models using an absolute filepath, so you can import models from any location on your computer. Please check the [import models using absolute file
```suggestion
Starting from version 0.4.7, Jan has introduced the capability to import models using an absolute file path. It allows you to import models from any directory on your computer. Please check the [import models using absolute filepath](../import-models-using-absolute-filepath) guide for more information.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/04-using-models/03-import-models-using-absolute-filepath.mdx
> +Navigate to the `~/jan/models` folder. Create a folder named `<modelname>`, for example, `tinyllama` and create a `model.json` file inside the folder including the following configurations:
```suggestion
1. Navigate to the `~/jan/models` folder. 
2. Create a folder named `<modelname>`, for example, `tinyllama`.
3. Create a `model.json` file inside the folder, including the following configurations:
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/04-using-models/03-import-models-using-absolute-filepath.mdx
> +- Ensure the filename must be `model.json`.
Since we already asked the users to create a `model.json`, we should remove this.

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/04-using-models/03-import-models-using-absolute-filepath.mdx
> +- Windows users may need to use double backslashes in the `url` property, for example: `C:\\Users\\username\\filename.gguf`.
```suggestion
- If you are using Windows, you need to use double backslashes in the url property, for example: C:\\Users\\username\\filename.gguf.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/04-using-models/03-import-models-using-absolute-filepath.mdx
> +Restart Jan and navigate to the Hub. Locate your model and click the Use button.
```suggestion
1. Restart Jan and navigate to the **Hub**. 
2. Locate your model and click the **Use** button.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/05-integrate-lmstudio.mdx
> +Navigate to the `Local Inference Server` on the LM Studio application, and select the model you want to use. Then, start the server after configuring the server port and options.
```suggestion
1. Navigate to the `Local Inference Server` on the LM Studio application.
2. Select the model you want to use. 
3. Start the server after configuring the server port and options.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +Firstly, you can select the model you want to use from the [Ollama library](https://ollama.com/library). Then, run your model by using the following command:
```suggestion
1. Select the model you want to use from the [Ollama library](https://ollama.com/library). 
2. Run your model by using the following command:
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +According to the [Ollama documentation on OpenAI compatibility](https://github.com/ollama/ollama/blob/main/docs/openai.md), you can use the `http://localhost:11434/v1/chat/completions` endpoint to in
```suggestion
3. According to the [Ollama documentation on OpenAI compatibility](https://github.com/ollama/ollama/blob/main/docs/openai.md), you can use the `http://localhost:11434/v1/chat/completions` endpoint to interact with the Ollama server. Thus, modify the `openai.json` file in the `~/jan/engines` folder to include the full URL of the Ollama server.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +Navigate to the `~/jan/models` folder. Create a folder named `<ollam-modelname>`, for example, `lmstudio-phi-2` and create a `model.json` file inside the folder including the following configurations
```suggestion
1. Navigate to the `~/jan/models` folder. 
3. Create a folder named `<ollam-modelname>`, for example, `lmstudio-phi-2` 
3. Create a `model.json` file inside the folder, including the following configurations:
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +- Ensure the filename must be `model.json`.
Suggest to remove this one

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +- Ensure the `id` property is set to the model name as Ollama model name.
```suggestion
- Set the `id` property as the Ollama model name.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +- Ensure the `format` property is set to `api`.
```suggestion
- Set the `format` property to `api`.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +- Ensure the `engine` property is set to `openai`.
```suggestion
- Set the `engine` property to `openai`.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +- Ensure the `state` property is set to `ready`.
```suggestion
- Set the `state` property to `ready`.
```

2024-02-21 02:56 UTC, cahyosubroto commented on docs/docs/guides/07-integrations/06-integrate-ollama.mdx
> +Restart Jan and navigate to the Hub. Locate your model and click the Use button.
```suggestion
1. Restart Jan and navigate to the **Hub**. 
2. Locate your model and click the **Use** button.
```

2024-02-21 14:02 UTC, hieu-jan commented
Hi @cahyosubroto could you re-review this PR, I resolved all conservation based on your suggestion. But request change currently block the PR merge.

2024-02-22 02:27 UTC, cahyosubroto approved these changes
LGTM!

2024-02-22 02:36 UTC, merged