Hero image compressed and Color Palette changed
janhq/jan pull request #213
Opened 2023-09-27 04:00 UTC by drakehere

- compressing the hero image
- Updating the color palette for Docs from Green -> Blue

2023-10-02 04:43 UTC, 0xSage requested changes

2023-10-02 04:43 UTC, 0xSage commented on docs/docusaurus.config.js
> +        hideOnScroll: true,
Let's not hide on scroll, bad ux.

2023-10-02 04:43 UTC, 0xSage commented on docs/src/css/custom.css
>    --ifm-color-primary-light: #29d5b0;
dark mode highlighting is still Docusaurus green. Is that what we want?

2023-10-02 04:43 UTC, 0xSage commented on docs/static/img/desktop-explore-models-dark.png
Can we have a light mode

2023-10-02 04:43 UTC, 0xSage commented on docs/static/img/desktop-explore-models.png
Can we have a dark mode as well

2023-10-02 04:43 UTC, 0xSage commented on docs/src/components/Homepage/hero.js
> +        <div className="py-24 sm:py-32 lg:pb-40 animate-in fade-in zoom-in-50 duration-1000 ">
Can we fix the glitch as a result of this animation. 
To repro:
1. hard refresh the site
2. observe glitch where copy shows up, then disappears, and animates up again.

2023-10-02 04:43 UTC, 0xSage commented on docs/src/components/Homepage/hero.js
> +                Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui
Why are we deleting valid copy and adding invalid copy?

2023-10-02 09:24 UTC, drakehere commented on docs/static/img/desktop-explore-models.png
Dark mode screenshot has been added

<img width="1706" alt="Screenshot 2023-10-02 at 16 24 01" src="https://github.com/janhq/jan/assets/139204511/b6eae4c7-de3e-432d-8e32-06c89a4250ab">

2023-10-02 09:43 UTC, drakehere commented
New updates:
- Dark and Light mode for each screenshot
- Hero section's copies are back
- Dark mode now have link and button highlighted in Blue

https://www.loom.com/share/98f9c40d904a4dcfb37e4c6a7cadfc7d?sid=8d9cff48-0325-4614-a204-971e972df3a7

2023-10-03 05:44 UTC, 0xSage approved these changes

2023-10-03 05:44 UTC, 0xSage commented
@drakehere approved, pls feel free to merge

2023-10-03 06:19 UTC, merged