Updated model configuration for 'Jan' to use AUTODETECT
janhq/jan pull request #2205
Opened 2024-03-01 13:41 UTC by pedx-ko

model configuration has been updated to use the ‘AUTODETECT’ setting. This change suggests that the system will now automatically detect the appropriate model to select

## Describe Your Changes

-

## Fixes Issues

- Closes #
- Closes #

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

2024-03-01 13:43 UTC, pedx-ko commented
updating doc

2024-03-05 10:19 UTC, 0xSage requested changes

2024-03-05 10:19 UTC, 0xSage commented on docs/docs/guides/07-integrations/01-integrate-continue.mdx
> +      "AUTODETECT",
Hey @pedx-ko , this line breaks the `config.json`. 
Can you link to where Continue now autodetects models?

2024-03-28 03:10 UTC, louis-jan commented
Should belong to docs repo instead. cc @Van-QA @urmauur

2024-03-28 03:10 UTC, closed without merging