docs: Implement Sidebar categories and Update guides content
janhq/jan pull request #2273
Opened 2024-03-07 11:43 UTC by aindrajaya

## Sidebar categories and Update guides content
- Add FAQs content
- Add Groq integration content
- Update Sidebar categories

## Fixes Issues

- Closes #2229 

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [x] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

2024-03-07 14:59 UTC, hieu-jan commented on docs/sidebars.js
>    guidesSidebar: [
For guidesSidebar: I think we should keep as current method autogenerated. 

Current change made sidebar broken, not good UX/ UI

![image](https://github.com/janhq/jan/assets/150573299/5b4f50dc-ac5d-47c0-ac3f-b548658e5746)

2024-03-07 15:20 UTC, hieu-jan commented on docs/docs/guides/integration/groq.mdx
> +    "author": "Your Name",
Author should set based on model https://console.groq.com/docs/models. `Meta` for Llama2 and `Mistral`  for mixtral-8x7b-32768

2024-03-07 15:21 UTC, hieu-jan commented on docs/docs/guides/integration/groq.mdx
> +  "engine": "groq"
engine should be `openai`

2024-03-07 15:25 UTC, hieu-jan commented on docs/docs/guides/faq.mdx
> +  - The feature to use local files is currently in development. For more information, please our offical [Discord](https://discord.com/invite/FTk2MvZwJH) for the latest update.
Typo `please our official`

2024-03-07 15:26 UTC, hieu-jan commented on docs/docs/guides/faq.mdx
> +  - Yes you can customize the installation path. Please see [here](https://github.com/janhq/jan/issues/1010) for more information.
Better to point to advanced settings `https://jan.ai/guides/advanced-settings/#access-the-jan-data-folder`

2024-03-07 15:26 UTC, hieu-jan commented on docs/docs/guides/integration/groq.mdx
> +- Access to the Jan platform
Jan application

2024-03-07 15:29 UTC, hieu-jan requested changes
There are some issues in current PRs

2024-03-07 18:15 UTC, cahyosubroto commented on docs/sidebars.js
>    guidesSidebar: [
Hi @hieu-jan appreciate the feedback! Let's discuss this with @0xSage and @dan-jan in our next meeting

2024-03-09 10:52 UTC, hieu-jan approved these changes
LGTM!

2024-03-09 10:53 UTC, merged