feat: revamp homepage
janhq/jan pull request #2332
Opened 2024-03-12 12:41 UTC by urmauur

## Describe Your Changes

![Screenshot 2024-03-14 at 17 23 50](https://github.com/janhq/jan/assets/10354610/4a1b7150-e33f-4877-afac-aef06a53fd39)

![Screenshot 2024-03-14 at 17 24 32](https://github.com/janhq/jan/assets/10354610/9a6fadea-6412-4422-a717-563dabb65d72)

## Fixes Issues

- #2219 

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

2024-03-13 04:56 UTC, 0xSage requested changes

2024-03-13 04:56 UTC, 0xSage commented on docs/src/pages/index.js
> +              Turn your computer into a{' '}
"into an" grammar check

2024-03-13 04:56 UTC, 0xSage commented on docs/src/pages/index.js
> +              downloads | Free & Open Source
Capitalize "Downloads"

2024-03-13 04:56 UTC, 0xSage commented on docs/src/pages/index.js
> +                400K+
Remove the blue/bold style, i thought it was a link. No need to stylize this. Let's not link it to anything.

2024-03-14 07:07 UTC, 0xSage commented
<img width="239" alt="image" src="https://github.com/janhq/jan/assets/69952136/bbbd8893-cfb2-467f-b3e7-4c30da1eea23">
bolding seems off

2024-03-19 06:02 UTC, hieu-jan approved these changes
LGTM!

2024-03-19 06:03 UTC, hieu-jan commented
All request changed are solved. Ready to merge!

2024-03-19 06:03 UTC, merged