feat: allowing user to fetch models from github
janhq/jan pull request #319
Opened 2023-10-10 14:19 UTC by namchuai

2023-10-10 14:46 UTC, louis-jan commented on electron/core/plugins/data-plugin/module.ts
> +          res(id);
2 resolves in 1 Promise

2023-10-10 15:33 UTC, louis-jan commented on electron/core/plugins/inference-plugin/module.js
> +async function initModel(fileName) {
Nice

2023-10-10 15:35 UTC, louis-jan commented on electron/core/plugins/data-plugin/module.ts
>          console.log(err);
no res -> nextjs fires error

2023-10-11 01:56 UTC, namchuai commented on electron/core/plugins/data-plugin/module.ts
> +          res(id);
I think it's ok since we have the `return` for each `resolve`

2023-10-11 02:41 UTC, louis-jan commented on electron/core/plugins/model-management-plugin/index.js
> +const getConfiguredModels = async () =>
remove async

2023-10-11 02:41 UTC, louis-jan commented on electron/core/plugins/model-management-plugin/index.js
> +  new Promise(async (resolve) => {
remove async

2023-10-11 02:43 UTC, louis-jan commented on electron/core/plugins/data-plugin/module.ts
> +          res(id);
Not this case, I mean 2 resolves for both stmts, we don't know which stmt would finish before the other.

2023-10-11 03:32 UTC, 0xSage commented
It works for me :).

Can we: 
- Show a quick loading state (spinner - whatever is easy) when we are pulling models, the initial 2 seconds of blank screen is a bit jarring
- Models' labels are incorrect and the contents don't show up. See original issue description/designs for what the labels should be

<img width="670" alt="image" src="https://github.com/janhq/jan/assets/69952136/1c3fa7e0-b61a-4a86-8bcf-1f3bbd86eba0">

<img width="765" alt="image" src="https://github.com/janhq/jan/assets/69952136/3a51cdca-5d4e-402c-b6af-08aa8bd67f3e">


- Is this logic incorporated yet? https://github.com/janhq/jan/issues/303#issuecomment-1752319805
- I have 8GB, but the 7.86 shows up as recommended.
<img width="771" alt="image" src="https://github.com/janhq/jan/assets/69952136/2e82fc71-5cbf-4b11-a794-db0ad56e43f9">

2023-10-11 03:37 UTC, 0xSage commented
Download button doesn't work: 
1. Go to Explore Models
2. Click download `llama-2-chat-GGUF`
3. Get the following error:
```sh
Unhandled Runtime Error
Error: Error invoking remote method 'invokePluginFunc': reply was never sent
```

<img width="1466" alt="image" src="https://github.com/janhq/jan/assets/69952136/598614ed-992a-4c63-beba-dc121924373e">

2023-10-11 03:39 UTC, 0xSage commented
Bug: Clicking on the expanded download link also doesn't work

1. Go to Explore Models
2. Click Download link next to` llama-2-13b-chat.gguf.q4_0.bin`
3. Get errors

```
Uncaught Exception:
Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: model_versions.id

localhost/:1 Uncaught (in promise) Error: Error invoking remote method 'invokePluginFunc': reply was never sent
```
<img width="633" alt="image" src="https://github.com/janhq/jan/assets/69952136/ae8d5bb2-77e8-4c06-96c5-4034daff2ec4">

2023-10-11 03:40 UTC, 0xSage requested changes
Hey @namchuai , there are a lot of issues with this PR. Please see the comments in Conversations and resolve before merging.

2023-10-11 04:11 UTC, namchuai commented
I believe most of the issue is related to the version of the plugins. Let me try to reproduce by do a clean slate install.

2023-10-11 07:07 UTC, namchuai commented
@0xSage , please try again with a clean slate test.
1. remove the app
2. run Jan by `yarn && yarn build:plugins && yarn dev`
3. go to settings -> Reload plugins
4. go to settings, ensure that the version is `1.0.1` for `Data Plugin`

About the recommended model not working as expected, it's because inside the model config, I putted it the same value for `maxRamRequired`: https://github.com/janhq/models/blob/main/bhlim-llama-2-chat-GGUF.json
I'm not sure what is the correct number for the ram required.

I think I made a spelling mistake, should be `minRamRequired` instead of `maxRamRequired`

2023-10-12 03:43 UTC, 0xSage commented
![image](https://github.com/janhq/jan/assets/69952136/e0207e93-e2a4-4e3a-8c85-930bb5f1b733)
add labels to versions as well than kyou

2023-10-12 04:57 UTC, 0xSage commented
I was only able to reproduce this issue in this branch, but not the current `main` branch. So the error is introduced by this PR. 

It seems like a SQLITE_ERROR related how we used to track model_versions?

It also only happens one time, right after the app is first built+started.

Maybe @louis-jan has some insights.

Error: 

```sh
Unhandled Runtime Error
Error: Error invoking remote method 'invokePluginFunc': Error: SQLITE_ERROR: no such table: model_versions
```

To repro:
1. Completely purge all app builds/cache
2. Checkout this branch
3. yarn build -> yarn dev
4. App starts with this error

@namchuai Lets absolutely fix this before merging, otherwise all new users will be greeted by an ERROR.

2023-10-12 07:34 UTC, namchuai commented
<img width="1562" alt="Screenshot 2023-10-12 at 00 34 20" src="https://github.com/janhq/jan/assets/10397206/d1634cff-189e-4fe1-a0b1-6a9868e37cd0">

2023-10-12 09:19 UTC, 0xSage commented
Everything else looks good. 

Error no longer shows up for the user, but shows up in terminal: 

```sh
$ yarn workspace jan-electron dev
$ tsc -p . && electron .
[1] 2023-10-12 17:15:07.546 Electron[53610:6055333] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[1] start migration: undefined
[1] (node:53610) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
[1] (Use `Electron --trace-deprecation ...` to show where the warning was created)
[1] [Error: ENOENT: no such file or directory, lstat '/Users/nicolezhu/Library/Application Support/jan-electron/plugins'] {
[1]   errno: -2,
[1]   code: 'ENOENT',
[1]   syscall: 'lstat',
[1]   path: '/Users/nicolezhu/Library/Application Support/jan-electron/plugins'
[1] }
[1] migrate plugins done
[1] Skip checkForUpdates because application is not packed and dev update config is not forced
[0] - wait compiling /_error (client and server)...
[0] - event compiled client and server successfully in 1280 ms (4046 modules)
[1] Database located at /Users/nicolezhu/Library/Application Support/jan-electron/jan.db
[1] Error: SQLITE_ERROR: no such table: model_versions
[1] --> in Database#all('SELECT * FROM model_versions WHERE finish_download_at != -1 ORDER BY finish_download_at DESC', [Function (anonymous)])
[1]     at modelVersions (/Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/dist/module.js:159:20)
[1]     at new Promise (<anonymous>)
[1]     at Object.<anonymous> (/Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/dist/module.js:158:41)
[1]     at Generator.next (<anonymous>)
[1]     at /Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/dist/module.js:7:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/dist/module.js:3:12)
[1]     at Object.getFinishedDownloadModels (/Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/dist/module.js:154:12)
[1]     at /Users/nicolezhu/jan/electron/build/main.js:177:58
[1]     at step (/Users/nicolezhu/jan/electron/build/main.js:44:23)
[1]     at Object.next (/Users/nicolezhu/jan/electron/build/main.js:25:53)
[1]     at /Users/nicolezhu/jan/electron/build/main.js:19:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/Users/nicolezhu/jan/electron/build/main.js:15:12)
[1]     at /Users/nicolezhu/jan/electron/build/main.js:171:16 {
[1]   errno: 1,
[1]   code: 'SQLITE_ERROR',
[1]   __augmented: true
[1] }
[1] Inserting {"model":{"id":"TheBloke/Mistral-7B-Instruct-v0.1-GGUF","name":"Mistral-7B-Instruct-v0.1-GGUF","shortDescription":"some description","avatarUrl":"https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6426d3f3a7723d62b53c259b/tvPikpAzKTKGN5wrpadOJ.jpeg?w=200&h=200&f=face","author":"The Bloke","version":"1.0.0","modelUrl":"https://google.com","nsfw":false,"tags":["freeform","tags"],"greeting":"Hello there","type":"LLM","createdAt":0,"longDescription":"GGUF is a new format introduced by the llama.cpp team on August 21st 2023. It is a replacement for GGML, which is no longer supported by llama.cpp. GGUF offers numerous advantages over GGML, such as better tokenisation, and support for special tokens. It is also supports metadata, and is designed to be extensible.","status":"Downloadable","releaseDate":0,"availableVersions":[{"id":"The Bloke-mistral-7b-instruct-v0.1.Q2_K.gguf","name":"mistral-7b-instruct-v0.1.Q2_K.gguf","quantMethod":"Q2_K","bits":2,"size":3080000000,"maxRamRequired":5580000000,"usecase":"smallest, significant quality loss - not recommended for most purposes","downloadLink":"https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q2_K.gguf","productId":"TheBloke/Mistral-7B-Instruct-v0.1-GGUF","startDownloadAt":1697102148195}]},"modelVersion":{"id":"The Bloke-mistral-7b-instruct-v0.1.Q2_K.gguf","name":"mistral-7b-instruct-v0.1.Q2_K.gguf","quantMethod":"Q2_K","bits":2,"size":3080000000,"maxRamRequired":5580000000,"usecase":"smallest, significant quality loss - not recommended for most purposes","downloadLink":"https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q2_K.gguf","productId":"TheBloke/Mistral-7B-Instruct-v0.1-GGUF","startDownloadAt":1697102148195}}
```

Optional to fix this in this PR or in a separate PR. Thank you @namchuai

2023-10-12 14:29 UTC, namchuai commented
@0xSage yes, the reason behind is the race condition when first time install the app, the query goes before the database is fully initialized, hence the table is not there yet.

In the future, we should have synchronized the init database before any query can be performed.

Since it's not the problem with this PR, please add the review and merge to unblock other devs.

2023-10-12 14:33 UTC, hiento09 approved these changes

2023-10-12 15:06 UTC, louis-jan commented
@0xSage @namchuai I'm revamping the database structure, all of the issues above are no longer relevant with my PR. Please proceed, merge and I will take care of these (I will need to rebase this to address). Please be noticed that most of these queries will be moved out of the data plugin.

2023-10-12 15:43 UTC, louis-jan approved these changes

2023-10-13 01:48 UTC, 0xSage approved these changes

2023-10-13 01:49 UTC, 0xSage commented
Lgtm!

2023-10-13 02:20 UTC, merged