#255: Monitoring plugin to web
janhq/jan pull request #320
Opened 2023-10-11 02:49 UTC by nam-john-ho

2023-10-14 09:50 UTC, louis-jan requested changes

2023-10-14 09:50 UTC, louis-jan commented on electron/core/plugins/data-plugin/index.ts
> +    if (typeof window !== "undefined" && typeof window.middleware !== "undefined") {
Rebase main, now it accesses "core" module only. Don't have to update module since latest main.

2023-10-14 09:50 UTC, louis-jan commented on electron/core/plugins/data-plugin/index.ts
> +    if (typeof window !== "undefined" && typeof window.middleware !== "undefined") {
Same as above

2023-10-14 09:50 UTC, louis-jan commented on electron/core/plugins/data-plugin/module.ts
> -    const db = new sqlite3.Database(
Let's rebase and discard db code changes

2023-10-14 09:50 UTC, louis-jan commented on electron/core/plugins/model-management-plugin/module.js
> +function getAppPath(){
I will add this api to @janhq/plugin-core

2023-10-14 09:50 UTC, louis-jan commented on electron/core/plugins/plugin.json
> +[
This should be load from web, not plugin. And access from core module

2023-10-14 09:50 UTC, louis-jan commented on server/main.ts
> +app.post('/api/v1/chatCompletion', (baseRequest: Request, baseReponse: Response) => {
This will be refactored as "plugin level"

2023-10-14 09:50 UTC, louis-jan commented on web/public/plugins/data-plugin/index.js
These should be packaged using yarn command, since /plugins now will be moved to the root dir

2023-10-19 04:58 UTC, 0xSage commented on server/main.ts
> +app.use((err: Error, req: Request, res: Response, next: Function) => {
handle ts error: `Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.`

2023-10-19 05:01 UTC, 0xSage commented on server/main.ts
> +      result = `File not exist: ${err}`;
Pls check grammar: "File does not exist"

2023-10-19 05:03 UTC, 0xSage commented on server/main.ts
> +app.post('/api/v1/invokeFunction', (req: Request, res: Response) => {
Very long function. Consider refactoring. Please add code comments

2023-10-19 05:06 UTC, 0xSage commented on server/main.ts
> +const downloadModel = (downloadUrl: string, fileName: string) => {
Why doesn't does fn return a promise?

2023-10-19 05:24 UTC, 0xSage requested changes

2023-10-19 05:24 UTC, 0xSage commented on server/main.ts
> +const deleteFile = (filePath: string) => {
Why doesn't this fn return a promise? As a result of this, it doesn't allow for any error handling, in fact we're just console.logging the `errors`, and expecting the user of this function to know exactly what error states to look for, which is very bad practice.

2023-10-19 05:24 UTC, 0xSage commented on server/main.ts
> +const downloadingFile = (): any | undefined => {
Why to define the return var if you can. Otherwise this code is hard to read.

2023-10-19 05:24 UTC, 0xSage commented on plugins/model-management-plugin/index.ts
> +    clearInterval(intervalId);
code is duplicated?

2023-10-19 05:24 UTC, 0xSage commented on plugins/model-management-plugin/index.ts
> +  else {
This code block is not well restructured. Pls refactor.

2023-10-19 10:28 UTC, nam-john-ho commented on server/main.ts
> +      result = `File not exist: ${err}`;
Fixed

2023-10-19 10:29 UTC, nam-john-ho commented on server/main.ts
> +const downloadModel = (downloadUrl: string, fileName: string) => {
Fixed

2023-10-19 10:29 UTC, nam-john-ho commented on server/main.ts
> +const deleteFile = (filePath: string) => {
Fixed

2023-10-19 10:29 UTC, nam-john-ho commented on server/main.ts
> +const downloadingFile = (): any | undefined => {
Fixed

2023-10-19 10:29 UTC, nam-john-ho commented on plugins/model-management-plugin/index.ts
> +    clearInterval(intervalId);
Fixed

2023-10-19 10:29 UTC, nam-john-ho commented on plugins/model-management-plugin/index.ts
> +  else {
Fixed

2023-10-23 09:11 UTC, louis-jan commented on electron/core/plugin-manager/execution/facade.js
> +import plugins from "../../../../web/public/plugins/plugin.json"
I will move this to web part

2023-10-23 09:12 UTC, louis-jan commented on electron/core/plugin-manager/execution/facade.js
> +import plugins from "../../../../web/public/plugins/plugin.json"
Should we define this in middleware?

2023-10-23 09:16 UTC, louis-jan commented on web/types/index.d.ts
> +    pluggableElectronIpc?: any | undefined
I don't see any ts file access this

2023-10-23 09:19 UTC, louis-jan commented on web/public/plugins/plugin.json
> +[
Pull from plugin manifest, we don't need this file

2023-10-23 09:25 UTC, louis-jan commented on web/app/page.tsx
> +import { executeSerial } from "../../electron/core/plugin-manager/execution/extension-manager";
let's import executeSerial from pluginService.ts

2023-10-30 04:31 UTC, louis-jan commented on plugins/inference-plugin/module.ts
> +  return process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Preferences' : process.env.HOME + "/.local/share");
should be from core > window.coreAPI

2023-10-30 04:33 UTC, louis-jan commented on .github/workflows/jan-electron-build.yml
> +      #     p12-password: ${{ secrets.CODE_SIGN_P12_PASSWORD }}
why comment out all of this?

cc @hiento09

2023-10-30 04:34 UTC, louis-jan commented on electron/core/plugin-manager/execution/facade.js
> +import plugins from "../../../../web/public/plugins/plugin.json"
import from plugin-catalog, new plugin manifest attribute: `supportCloudNative`

2023-10-30 04:36 UTC, louis-jan commented on electron/core/plugin-manager/execution/facade.js
> -  const plgList = await window.pluggableElectronIpc.getActive();
Discard the changes, just const plgList = await window.pluggableElectronIpc?.getActive() ?? []; is good enough

2023-10-30 04:38 UTC, louis-jan commented on web/screens/Settings/index.tsx
> +if (typeof window !== "undefined" && typeof window.electronAPI !== "undefined") {
discard

2023-10-30 04:39 UTC, louis-jan commented on web/services/coreService.ts
> +function openExternalUrl(url: string) {
Refactor to cloudNativeService.ts

2023-10-30 04:46 UTC, hiento09 commented on .github/workflows/jan-electron-build.yml
> +      #     p12-password: ${{ secrets.CODE_SIGN_P12_PASSWORD }}
This comes from an outdated commit, please undo the comment @nam-john-ho

2023-10-30 05:46 UTC, louis-jan commented on web/services/coreService.ts
> +import { invokePluginFunc, downloadFile, deleteFile, appVersion, openExternalUrl } from "./cloudNativeService"
import * as cn from "./cloudNativeService"

2023-10-30 05:47 UTC, louis-jan commented on web/services/coreService.ts
> +      invokePluginFunc,
with the changes `import * as cn` above
=> 
cn.invokePluginFunc,

2023-10-30 07:59 UTC, louis-jan approved these changes

2023-10-30 09:46 UTC, louis-jan commented on server/main.ts
> +const fs = require("fs");
import from fs above, then require again. Let's combine import

2023-10-30 09:46 UTC, louis-jan commented on server/main.ts
> +const path = require("path");
same as above

2023-10-30 10:11 UTC, louis-jan commented on web/services/cloudNativeService.ts
> +import { version } from '../../package.json';
Webpack

2023-10-31 02:49 UTC, 0xSage approved these changes

2023-10-31 02:51 UTC, merged