docs: add OpenAI swagger file
janhq/jan pull request #623
Opened 2023-11-15 07:06 UTC by hieu-jan

Add OpenAIAPI.yaml from https://github.com/openai/openai-openapi

2023-11-16 08:23 UTC, dan-jan requested changes

2023-11-16 08:23 UTC, dan-jan commented on docs/docusaurus.config.js
> +            spec: "openapi/OpenAIAPI.yaml", // can be local file, url, or parsed json object
We should rename this to Jan.yaml, and customize it to fit our API. 

Quick check: was OpenAI's OpenAPI spec under any license? If it is licensed, we may have to re-draft it from scratch. :/

2023-11-16 08:23 UTC, dan-jan commented on docs/docusaurus.config.js
> +            route: "/api"
I would recommend `/api-reference`, as we may use `/api` in the future for an actual API.

2023-11-16 08:23 UTC, dan-jan commented on docs/openapi/OpenAPISpec.json
> +          "description": "***\nThe GraphQl query for this endpoint is:\n``` graphql\nquery MyQuery {\n  collections {\n    id\n    name\n    slug\n  }\n}\n```",
What is this GraphQL query for? (seems very outdated)

2023-11-16 16:18 UTC, hieu-jan commented on docs/openapi/OpenAPISpec.json
> +          "description": "***\nThe GraphQl query for this endpoint is:\n``` graphql\nquery MyQuery {\n  collections {\n    id\n    name\n    slug\n  }\n}\n```",
This one is an old file from our code base. Just an example of import .json. Maybe the commit changed due to making a new line in the first line. I will remove this file too.

2023-11-16 16:23 UTC, hieu-jan commented on docs/docusaurus.config.js
> +            spec: "openapi/OpenAIAPI.yaml", // can be local file, url, or parsed json object
Yeah, it's under an MIT license. Re-draft it from initial is also fit with our need too.

2023-11-16 16:33 UTC, hieu-jan commented on docs/docusaurus.config.js
> +            spec: "openapi/OpenAIAPI.yaml", // can be local file, url, or parsed json object
This file is under MIT license. Re-draft it from scratch may be a better option for us as we will customize some parts too

2023-11-18 20:21 UTC, dan-jan commented
@hieu-jan Please remove the `yarn.lock` from your PR

2023-11-19 03:16 UTC, hieu-jan commented
Re-solved all conversation and conflicts with main branch

2023-11-19 03:21 UTC, dan-jan approved these changes
Preliminary approve

2023-11-19 03:23 UTC, merged