docs: re-structure installation
janhq/jan pull request #634
Opened 2023-11-15 14:46 UTC by hieu-jan

The purpose of this pull request is to restructure the installation documentation (#632)

2023-11-16 06:54 UTC, dan-jan requested changes

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/macOS.md
> +### Does Jan run on Apple silicon machines?
"Silicon"

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/macOS.md
> +6. Once installation is complete, you can launch Jan by clicking on the Jan icon.
Personally, I don't think we need to provide this sort of step-by-step instruction. Documentation should provide the right directions for people to find things, and trust people's ability to figure things out. 

In other words, don't say "click this", "click that" unless absolutely necessary OR referring to a confusing system designed by someone else
- If you have to give that kind of instruction, then it's a design problem (should be intuitive)
- You should then raise it up to @0xSage @imtuyethan to find a design solution 

## Download Directions

I would say Jan can be downloaded from: 

1. https://jan.ai (homepage)
2. Github Releases page (give instructions on which architecture to choose)
    - Intel Macs (i.e. choose Mac x86 dmg)
    - Apple Silicon M1, M2, M3 Macs (i.e. Mac ARM dmg)

## Which Package should I download?
For Mac installation, there's a lot of issues where people don't even know there is a difference between Intel Macs and Apple Silicon Macs. Documentation should cover this difference, and explain how to find out what architecture/processor type they are on

- Processor type (i.e. "About This Mac")
- RAM

After that, we need to explain how M1, M2, M3 -> "Choose ARM". And "Intel" = "Choose x86". 
You may need to link up with @hiento09 to verify package names, as I believe he is defining it in CI/CD. 

## RAM
Local Inference is very RAM-heavy. We should have some recommendations here for hardware minimum requirements. 

I would recommend linking to external Apple documentation for "About This Mac" (vs. writing our own).

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/overview.md
> +Jan is a small download (<100 MB) and has a disk footprint of under 300 MB. Being a lightweight platform, it should run smoothly on modern hardware. Additionally, as you will download, store and run
Are we sure we are less than <100mb? I believe we went over recently

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/overview.md
> +- At least 8 GB of RAM
We need to explain the different requirements for RAM and GPU VRAM. 

- RAM: using traditional computer
- VRAM: using GPU

We should also talk about how RAM and VRAM sizes relate to models that you can run, e.g: 

- 8gb of RAM of VRAM can only realistically run smaller models, e.g. 3B models or quantized 7B models
- 16gb is recommended as the "minimum usable models" are mostly at 7b (e.g. Mistral 7b)
- The really good models (e.g. 70b models) require at least X gb of RAM

You may need to do some reading up on r/localllama, and have a call with @hahuyhoang411 to get up to speed on this.

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/overview.md
> +- Windows (64-bit)
We should also talk about CPU and GPU support. 

CPU: 
- ARM
- x86

GPU: 
- Nvidia (thru llama.cpp)
- Talk about additional support coming soon for AMD and Intel

For the GPU portion, you will need to get 15min of @tikikun's time to grok which GPU architectures we currently support, and what we don't.

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/windows.md
> -## Step 2: Proceed the Windows Defender
These may be good to retain in the FAQ or Troubleshooting for Windows.

2023-11-16 06:54 UTC, dan-jan commented on docs/docs/getting-started/install/macOS.md
> +Yes, Jan supports macOS Arm64 builds that can run on Macs with the Apple silicon chipsets. You can install this version of Jan by clicking on the **Download for Mac (M1/M2)** version from the [downlo
I would recommend an "Uninstall" section for Mac, that covers the directories to wipe clean in 
- `Application Support`

I think @0xSage covered some of them here (for Mac)
https://github.com/janhq/jan#troubleshooting

2023-11-16 06:54 UTC, dan-jan commented on docs/sidebars.js
> +            "getting-started/install/overview",
I wonder whether it makes more sense to have shorter paths, i.e. `jan.ai/install/windows`

Docusaurus "sidebar hierarchy" does not require actual file and path locations to be hierarchical, i.e. you can have a top-level folder in docs called "install"

2023-11-16 08:10 UTC, hieu-jan commented on docs/docs/getting-started/install/linux.md
> +2. Download the latest version of Jan for macOS by clicking on the **Download for Linux**.
Actually, I referred to some installation docs of mass products, they mostly used `macOS`, just I decided to change from `mac` from old version to `macOS`.

2023-11-16 08:17 UTC, hieu-jan commented on docs/docs/getting-started/install/overview.md
> +Jan is a small download (<100 MB) and has a disk footprint of under 300 MB. Being a lightweight platform, it should run smoothly on modern hardware. Additionally, as you will download, store and run
Double-check it, modified to <200mb as mac version recently went over 100 mb.

2023-11-16 08:33 UTC, hieu-jan commented on docs/sidebars.js
> +            "getting-started/install/overview",
Totally agree about it. I was thinking about it too. We can eliminate `getting-started` folder by moving the `install` folder under the docs

2023-11-16 11:26 UTC, hieu-jan commented on docs/docs/getting-started/install/linux.md
> +2. Download the latest version of Jan for macOS by clicking on the **Download for Linux**.
yeah it's a typo mistake, fixed it!! Thank you!

2023-11-20 01:01 UTC, closed without merging

2023-11-20 01:39 UTC, dan-jan commented
Wait, why did we close this?