Api refeference
janhq/jan pull request #679
Opened 2023-11-21 11:47 UTC by hahuyhoang411

- [ ] Model API
- [ ] Chat API
- [ ] Assistant API
- [ ] Messages API
- [ ] Threads API

2023-11-21 11:47 UTC, hahuyhoang411 commented
This is only the draft of the Model API.

2023-11-22 07:01 UTC, 0xSage commented on docs/openapi/specs/messages.yaml
> +      required:
none of these are required fields.

2023-11-22 07:01 UTC, 0xSage commented on docs/openapi/specs/messages.yaml
> +      required:
not required

2023-11-22 07:01 UTC, 0xSage commented on docs/openapi/specs/models.yaml
> +      required:
only required field is source_url

2023-11-22 07:01 UTC, 0xSage commented on docs/openapi/specs/threads.yaml
> +      required:
none of these fields are required

2023-11-22 07:02 UTC, 0xSage requested changes
1. Omit the docs/specs changes please. I'm working on that in a separate unmerged branch #681. Adding those unmerged changes in this PR will break my branch - this is not best practice. This PR should only update `/openapi/specs`. 

2. Typo in the title of this PR `Api refeference`

3. Majority fields are not required. Please read the docs/specs carefully - we specify which fields are required/not

2023-11-22 12:10 UTC, dan-jan commented
@hahuyhoang411 @hieu-jan: Updating the title of the PR (please observe naming hygiene!)

2023-11-24 03:22 UTC, 0xSage approved these changes
woot

2023-11-24 05:48 UTC, merged