docs: add assistants api reference
janhq/jan pull request #801
Opened 2023-12-01 01:15 UTC by hieu-jan

- [x] Solved issue #688 
- [x] Adding the requestBody and response for each assistant endpoint API
- [x] Run auto format for all .yaml files to make the code clean
- [x] Fixing some minor bugs in the API Reference page

2023-12-01 10:04 UTC, 0xSage reviewed
@hieu-jan a more accurate reference for assistants is here: http://localhost:3001/specs/assistants/#assistantjson

The github description is a bit outdated.

Pls fix then we're ready to merge! Thank you

2023-12-01 10:04 UTC, 0xSage commented on docs/openapi/specs/assistants.yaml
> +      required:
afaik none of the fields in assts are required

2023-12-04 01:28 UTC, hieu-jan commented
I have updated the assistant model. Currently fixing the request and response content of each API endpoint.

2023-12-07 19:11 UTC, hieu-jan commented
Hi @0xSage, I made some new change to the current version including
- [x] Adding requestBody and response for each assistant endpoint API
- [x] Run auto format for all .yaml files to make the code clean
- [x] Fixing some minor bugs of links, text in Models, Messages

2023-12-08 03:48 UTC, 0xSage requested changes
Hey, things look a bit better, but I think I mentioned in a previous PR that non of these fields are required: 

<img width="761" alt="image" src="https://github.com/janhq/jan/assets/69952136/02d84074-cc41-4f44-bd7c-d4906789e9c6">

2023-12-08 07:09 UTC, hieu-jan commented
Hi @0xSage, sorry for confusing you, I guess this image is from the old deployment version. In the current latest version, I already fixed this one too. https://f0d8c9d9.jan-qn8.pages.dev/api-reference

2023-12-08 09:33 UTC, merged